### PR TITLE
Use leaflet and react-leaflet as external packages

### PR DESCRIPTION
**Pull request by pikhovkin**
See the beginning [here](https://github.com/thedirtyfew/dash-leaflet/pull/146)

### CODE REVIEW

**Comment by pikhovkin** [comment]
[I also prepare the ground for the dependencies between the Dash components to work](https://github.com/plotly/dash/pull/2105). You could support my pull request.

**Comment by emilhe** [comment]
Sorry for the long wait time, I have been caught up in other stuff. In the raw form, I had some issues with resource loading while testing the PR. I have merged the PR though, and I am now working on getting the resource loading working. When I get it working, I will push a new release.

**Comment by pikhovkin** [comment]
@emilhe thank you for the merge. Now it remains for these guys to approve [this merge](https://github.com/plotly/dash/pull/2105) so that plugins work.

**Comment by pikhovkin** [comment]
@emilhe these external plugins will work when this [PR](https://github.com/plotly/dash/pull/2105) is merged

**Pull request merged**
