### PR TITLE
Add R and Julia packages

### PR DESCRIPTION
**Pull request by rpkyle**
This PR proposes to contribute R and Julia packages to the repository, along with modifications to `package.json` required to continue building them in the future. 

The R package will require examples for all functions (I have added a single example to `dash-info.yaml` for `dlMap` to demonstrate how we do this internally at Plotly) before CRAN will accept the package, but it should be generally ready once that's done in case you wish to do so [here](https://cran.r-project.org/submit.html).

### CODE REVIEW

**Comment by emilhe** [comment]
Thanks for the pull request! I am a little hesitant to add R and Julia support though, as i am not using these languages myself. Hence, unless i start doing so, i am not able to verify that the components are working as intended, nor provide any support.

**Comment by rpkyle** [comment]
No worries @emilhe! `dash-leaflet` is quite a neat package, I enjoyed trying it out. In case any other R or Julia users want to take a peek, the package will remain in my fork as-is.

**Comment by emilhe** [comment]
Thanks! I'll keep it in mind. For now, I'll focus on learning React and adding more components :)

**Comment by emilhe** [comment]
Did you check in the auto generated files on purpose? Usually, i would check in only the source code.

**Comment by rpkyle** [comment]
@emilhe When we build the components at Plotly, we typically merge the artifacts into `master` at release time, and host all versions (Python, R, Julia) in the same repository. Feel free to remove them if it makes sense for you.

**Pull request closed without merging**
